version: "3.1"
services:
  auth_server:
    build: ./backend/auth_server
    container_name: auth_server
    ports:
      - "3000:3000"
    depends_on:
      - mongo_auth
    environment:
      - MONGO_HOST=mongo_auth
    volumes:
      - ./backend/auth_server:/usr/src/app
  mongo_auth:
    image: mongo
    container_name: mongo_auth
    ports:
      - "27022:27017"
  product_catalog:
    build: ./backend/product_catalog
    container_name: product_catalog
    ports:
      - "3001:3001"
    depends_on:
      - mongo_catalog
    environment:
      - MONGO_HOST=mongo_catalog
    volumes:
      - ./backend/product_catalog:/usr/src/app
  mongo_catalog:
    image: mongo
    container_name: mongo_catalog
    ports:
      - "27023:27017"
  frontend:
    environment: 
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./frontend
    container_name: webshop_frontend
    volumes:
      - ./frontend:/home/frontend
    ports:
      - "8080:8080"
  nginx:
    build:
      context: ./nginx
    container_name: webshop_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/home
    depends_on:
      - auth_server
      - product_catalog
